spring:
    profiles:
        active:
          - EN
          - dog
          - prod
my:
    username: YmlUserName
    password: YmlPassword
    jdbcURL: YmlURL

---
spring:
    profiles: prod
my:
    username: YmlProdUserName
    password: YmlProdPassword
    jdbcURL: YmlProdURL